AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloud formation template for land plot project'

Parameters:
  TopicName:
    Type: String
    Description: Name for the SNS topic
    Default: 'course-events-topic'

Resources:
  CourseEventsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName
      DisplayName: !Ref TopicName
      Tags:
        - Key: Name
          Value: !Ref TopicName
        - Key: Environment
          Value: Sample

Outputs:
  SNSTopicName:
    Description: Name of the SNS topic
    Value: !GetAtt CourseEventsTopic.TopicName
  
  SNSTopicArn:
    Description: ARN of the SNS topic
    Value: !Ref CourseEventsTopic